### PR TITLE
feat: add gofumpt

### PR DESCRIPTION
**Pull request by ohlsont**
Add gofumpt for a stricter goformatting.

### CODE REVIEW

**Comment by ohlsont** [comment]
:D. I kind of wanted the formatting part of it so that things was automatically formatted

**Comment by Edholm** [comment]
> :D. I kind of wanted the formatting part of it so that things was automatically formatted

Alright, that part is already included in golangci-lint (using gofumpt no less)

**Comment by Edholm** [comment]
Previous PR and discussion: #102

**Comment by ohlsont** [comment]
Hmm I thought I search for a PR before making this

**Pull request closed without merging**
