### PR TITLE
feat(exec): add new public funcion `OutputWithErr`

### PR DESCRIPTION
**Pull request by felixmr1**
will also return an error, if any occurs.

### CODE REVIEW

**Review by Edholm — COMMENTED** [review]
We want to keep the public API minimal and stable. In this case we cater to the most common use-case. If you really think this will be useful across the whole ecosystem I say let's merge, otherwise I would probably say that write this func in the repo you want to use it :)

We actually started out with this setup in the beginning but actively chose to keep it minimal.

**Comment by felixmr1** [comment]
> We want to keep the public API minimal and stable. In this case we cater to the most common use-case. If you really think this will be useful across the whole ecosystem I say let's merge, otherwise I would probably say that write this func in the repo you want to use it :)
> 
> We actually started out with this setup in the beginning but actively chose to keep it minimal.

Gotcha! Yeah I rather have the error returned and let the user choose wether to panic or not.

**Comment by Edholm** [comment]
> > We want to keep the public API minimal and stable. In this case we cater to the most common use-case. If you really think this will be useful across the whole ecosystem I say let's merge, otherwise I would probably say that write this func in the repo you want to use it :)
> > We actually started out with this setup in the beginning but actively chose to keep it minimal.
> 
> Gotcha! Yeah I rather have the error returned and let the user choose wether to panic or not.

I would probably argue that you can write this in your repo without almost any overhead. I.e. copy the implementation of `Output` and remove the panic :)

It is basically a convenience func to avoid having to do an error check. The `cmd.Output` func is basically what you've implemented :)

**Comment by alethenorio** [comment]
Personally I find the `Output` function to almost not be needed here as it does very little compared to what you already get out of the Go stdlib and I'd rather get rid of it than introducing another one which also does very little.

**Comment by felixmr1** [comment]
Okidoki, ill just implement this locally then.

**Pull request closed without merging**
