### PR TITLE
bump deps

### PR DESCRIPTION
**Pull request by odsod**
- feat(api-linter): bump to 1.36.2
- feat(golangci-lint): bump to 1.50.0
- feat(goreleaser): bump to 1.11.5

### CODE REVIEW

**Review by alethenorio — APPROVED** [review]

**Comment by odsod** [comment]
@alethenorio The build failure looks like an issue with the `gci` linter - I'll have a look

**Comment by alethenorio** [comment]
I think we've had a few people recently run into trouble with `gci`. Doesn't always seem to fix stuff

**Comment by odsod** [comment]
It looks like several linters are tripping up on this specifically (gci, gofumpt)
image

**Comment by alethenorio** [comment]
The correct way as per golangci lint is no space `//nolint` so maybe we need to fix our code?

**Comment by Edholm** [comment]
I think the issue is that the bumped GCI inserts space, while other linters complains about the newly inserted space :(

**Comment by odsod** [comment]
I fixed it @Edholm @alethenorio - the issue was that nolint comments should not have a space after the `:` - that's what all the linters were going on about! we will have some lint errors from this, but now we are enforcing the correct formatting

**Pull request merged**
