### PR TITLE
feat(settings): bootstrap with inital settings

### PR DESCRIPTION
**Pull request by felixmr1**
I have left all the default entries, but have commented out stuff I feel is unessecary. And changed other ones to more einride-esq values (eg rebase merge over squash merge). 

Lets have some discussions around this one!

### CODE REVIEW

**Comment by alethenorio** [comment]
Would be great to get this under source control but does this means the application would overwrite whatever was done when the repo was created?

Since this would also require admin to the repo (maybe even the org) we should check if the tool can be trusted to do so

**Review by odsod — COMMENTED** [review]
Is this a GitHub-supported feature, or just developed by engineers who work at GitHub?

**Comment by felixmr1** [comment]
> Would be great to get this under source control but does this means the application would overwrite whatever was done when the repo was created?
> 
> 
> 
> Since this would also require admin to the repo (maybe even the org) we should check if the tool can be trusted to do so


Yes I think it will. I guess one would boostrap with a minimal config and make changes that is appropriate to the repo.

**Comment by felixmr1** [comment]
> Is this a GitHub-supported feature, or just developed by engineers who work at GitHub?

good question

https://github.com/apps/settings

**Comment by alethenorio** [comment]
Looks like it is not GitHub

Also saw this in the notes

```
WARNING: Note that this app inherently escalates anyone with push permissions to the admin role, since they can push config settings to the master branch, which will be synced
```

**Comment by Edholm** [comment]
If we go for something like this, would it be more suitable to put in our template repos?

**Comment by maxekman** [comment]
Eventually I think some kind of Einride repo-operator tool that constantly analyzes our repos and make suggestions in PRs is a good solution. It gives us all the power, and that operator tool can have privileges to also do other repo setting changes from an org-level.

**Comment by felixmr1** [comment]
> Looks like it is not GitHub
> 
> Also saw this in the notes
> 
> ```
> WARNING: Note that this app inherently escalates anyone with push permissions to the admin role, since they can push config settings to the master branch, which will be synced
> ```

saw that just now as well! that is a game breaker for this solution, imo!

**Comment by alethenorio** [comment]
It might not be the end of the world if the repo is set to require PR reviews but definitely gives something to think about

**Comment by odsod** [comment]
Let's put this on pause until next quarter and see what goes into the roadmap of @alethenorio's team?

**Comment by alethenorio** [comment]
Great idea. We can evaluate this soon as part of better automation across our repos

**Pull request closed without merging**
